"""
Django settings for djaws project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

# Import necessary modules
import os
import environ

# Initialize environment variables
env = environ.Env(
    # Set casting, default value
    DEBUG=(bool, True)
)
# Read .env file
environ.Env.read_env()

# Define base directory of the project
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Define path for React app
REACT_APP = os.path.join(os.path.join(BASE_DIR, 'frontend'),)

# Security settings
SECRET_KEY = env('SECRET_KEY')
DEBUG = True

# Global variables
PER_PAGE_ITEM = 24
BRAND_IMAGE = "https://cbs-static.s3.eu-west-2.amazonaws.com/static/images/pixly-wide-zip.jpg"
LIST_MIN_SUMMARY = 200

# Security configurations
SECURE_REDIRECT_EXEMPT = ['ads.txt']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CORS_REPLACE_HTTPS_REFERER = True
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_SECONDS = 1000000
SECURE_FRAME_DENY = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
