# Generated by Django 2.0.5 on 2018-11-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
