branch-defaults:
  default:
    environment: dra-1-6
  master:
    environment: dra-1-6
environment-defaults:
  dj-rest-03:
    branch: null
    repository: null
  dra-1-5:
    branch: null
    repository: null
  dra-1-6:
    branch: null
    repository: null
global:
  application_name: django
  default_ec2_keyname: cbs-ssh
  default_platform: Python 3.6
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
