branch-defaults:
  default:
    environment: dra-1-6
environment-defaults:
  dj-rest-03:
    branch: null
    repository: null
  dra-1-5:
    branch: null
    repository: null
global:
  application_name: django
  default_ec2_keyname: aws-eb
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.7.4
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
