# Generated by Django 2.0.5 on 2019-08-07 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0074_profile_should_change_password'),
        ('items', '0110_auto_20190729_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.CharField(blank=True, default='...', max_length=20000, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Profile', verbose_name='posts')),
                ('tag', models.ManyToManyField(blank=True, null=True, related_name='posts', to='items.Tag')),
            ],
        ),
    ]
