# Generated by Django 2.0.5 on 2019-08-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default='...', max_length=20000, null=True),
        ),
    ]
