# Generated by Django 2.0.5 on 2019-08-07 19:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0074_profile_should_change_password'),
        ('items', '0110_auto_20190729_2140'),
        ('blog', '0008_auto_20190807_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('header', models.CharField(blank=True, max_length=300, null=True)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='...', max_length=20000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', django_mysql.models.JSONField(default=dict)),
                ('active', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Profile', verbose_name='posts')),
                ('tag', models.ManyToManyField(blank=True, null=True, related_name='posts', to='items.Tag')),
            ],
        ),
    ]
