# Generated by Django 2.0.5 on 2019-08-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('t', 'Tech'), ('c', 'Cinema')], help_text='Type of post? (Tech, Cinema)', max_length=2, null=True),
        ),
    ]
