# Generated by Django 2.0.5 on 2019-08-07 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='persons.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('t', 'Tech'), ('c', 'Cinema'), ('o', 'Other')], help_text='Type of post? (Tech, Cinema)', max_length=2, null=True),
        ),
    ]
