# Generated by Django 2.0.5 on 2019-08-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
