# Generated by Django 2.0.5 on 2019-08-09 21:14

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=blog.models.post_poster_upload_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, help_text='A brief summary of text', max_length=500, null=True),
        ),
    ]
