# Generated by Django 2.0.5 on 2019-11-15 20:27

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_page',
            field=models.BooleanField(default=False, help_text='Selected item will be showed on welcome screen'),
        ),
        migrations.AddField(
            model_name='post',
            name='richdata',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_keywords',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_short_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
