# Generated by Django 2.0.5 on 2019-11-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20191115_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='cover_poster',
        ),
    ]
