# Generated by Django 2.0.5 on 2019-11-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20191116_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seo_description',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
    ]
