# Generated by Django 2.0.5 on 2019-11-17 21:48

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20191116_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html_content',
            field=froala_editor.fields.FroalaField(blank=True, max_length=20000, null=True),
        ),
    ]
