# Generated by Django 2.0.5 on 2019-11-17 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_post_html_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='html_content',
        ),
    ]
