# Generated by Django 2.0.5 on 2019-11-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_post_html_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover_poster',
            new_name='cover',
        ),
    ]
