# Generated by Django 2.0.5 on 2019-11-23 14:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20191122_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='...', help_text="Only Content, Don't add H1 Heading", max_length=60000, null=True),
        ),
    ]
