# Generated by Django 2.0.5 on 2018-10-15 19:15

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('summary', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(max_length=9, null=True)),
                ('tmdb_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(null=True)),
                ('summary', models.TextField(max_length=5000, null=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('poster', models.ImageField(blank=True, upload_to='posters/')),
                ('tags', django_mysql.models.SetTextField(models.CharField(max_length=15), default=set(), size=None)),
                ('data', django_mysql.models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('summary', models.CharField(max_length=2000, null=True)),
                ('link', models.URLField()),
                ('duration', models.IntegerField(help_text='seconds', null=True)),
                ('related_movies', models.ManyToManyField(blank=True, to='items.Movie')),
                ('related_persons', models.ManyToManyField(blank=True, to='persons.Person')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='movies',
            field=models.ManyToManyField(to='items.Movie'),
        ),
    ]
