# Generated by Django 2.0.5 on 2018-10-22 13:38

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=django_mysql.models.JSONField(default=dict, verbose_name={'dummy': {}, 'user': {}}),
        ),
    ]
