# Generated by Django 2.0.5 on 2018-10-22 15:29

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20181022_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ratings_dummy',
            field=django_mysql.models.SetCharField(models.CharField(max_length=15), default=set(), max_length=15, size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ratings_user',
            field=django_mysql.models.SetCharField(models.IntegerField(), default=set(), max_length=15, size=None),
        ),
    ]
