# Generated by Django 2.0.5 on 2018-10-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20181022_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acted', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directed', to='persons.Person'),
        ),
    ]
