# Generated by Django 2.0.5 on 2018-10-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20181022_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='related_persons',
            field=models.ManyToManyField(blank=True, related_name='videos', to='persons.Person'),
        ),
    ]
