# Generated by Django 2.0.5 on 2018-10-22 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20181022_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='video',
            name='related_movies',
            field=models.ManyToManyField(blank=True, related_name='videos', to='items.Movie'),
        ),
    ]
