# Generated by Django 2.0.5 on 2018-10-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_auto_20181022_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-id']},
        ),
    ]
