# Generated by Django 2.0.5 on 2018-10-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_itemimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemImage',
            new_name='MovieImage',
        ),
        migrations.RenameField(
            model_name='movieimage',
            old_name='person',
            new_name='movie',
        ),
        migrations.AlterField(
            model_name='video',
            name='related_movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='videos', to='items.Movie'),
        ),
        migrations.AlterField(
            model_name='video',
            name='related_persons',
            field=models.ManyToManyField(blank=True, null=True, related_name='videos', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='video',
            name='summary',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
