# Generated by Django 2.0.5 on 2018-10-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_auto_20181031_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='related_movies',
            field=models.ManyToManyField(blank=True, related_name='videos', to='items.Movie'),
        ),
        migrations.AlterField(
            model_name='video',
            name='related_persons',
            field=models.ManyToManyField(blank=True, related_name='videos', to='persons.Person'),
        ),
    ]
