# Generated by Django 2.0.5 on 2018-10-31 17:30

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20181031_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acted', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ratings_dummy',
            field=django_mysql.models.SetCharField(models.CharField(max_length=15), blank=True, default=set(), max_length=15, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ratings_user',
            field=django_mysql.models.SetCharField(models.IntegerField(), blank=True, default=set(), max_length=15, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=django_mysql.models.SetTextField(models.CharField(max_length=15), blank=True, default=set(), null=True, size=None),
        ),
    ]
