# Generated by Django 2.0.5 on 2018-11-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_auto_20181031_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='info',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='movieimage',
            name='info',
            field=models.CharField(blank=True, help_text="Enter the type of video category.\n E.g:'video-essay or interview or conversations'", max_length=40, null=True),
        ),
    ]
