# Generated by Django 2.0.5 on 2018-11-01 14:41

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_auto_20181101_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=django_mysql.models.ListTextField(models.CharField(max_length=20), max_length=20, null=True, size=None),
        ),
    ]
