# Generated by Django 2.0.5 on 2018-11-01 14:44

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_video_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=django_mysql.models.ListTextField(models.CharField(max_length=20), default=[], max_length=20, null=True, size=None),
        ),
    ]
