# Generated by Django 2.0.5 on 2018-11-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0031_auto_20181105_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='ratings_dummy',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='ratings_user',
        ),
    ]
