# Generated by Django 2.0.5 on 2018-11-06 16:34

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0033_auto_20181105_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ratings_user',
            field=django_mysql.models.SetTextField(models.CharField(max_length=15), blank=True, default=set(), null=True, size=None),
        ),
    ]
