# Generated by Django 2.0.5 on 2018-11-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0035_auto_20181109_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='movies',
            field=models.ManyToManyField(to='items.Movie'),
        ),
    ]
