# Generated by Django 2.0.5 on 2018-11-10 00:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0036_auto_20181109_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
        migrations.AddField(
            model_name='movie',
            name='lists',
            field=django_mysql.models.SetTextField(models.CharField(max_length=15), blank=True, default=set(), null=True, size=None),
        ),
    ]
