# Generated by Django 2.0.5 on 2018-11-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0037_auto_20181110_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='lists',
        ),
    ]
