# Generated by Django 2.0.5 on 2018-11-10 21:14

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0040_auto_20181111_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=django_mysql.models.ListTextField(models.CharField(max_length=40), default=[], help_text="Enter the type of video category.\n E.g:'video-essay or interview or conversations'", null=True, size=None),
        ),
    ]
