# Generated by Django 2.0.5 on 2018-11-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0022_profile_follow_lists'),
        ('items', '0042_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('profile', 'movie')},
        ),
    ]
