# Generated by Django 2.0.5 on 2018-11-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0043_auto_20181115_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
