# Generated by Django 2.0.5 on 2018-11-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0044_auto_20181115_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('summary', models.TextField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField(blank=True, max_length=5000, null=True)),
                ('lists', models.ManyToManyField(to='items.List')),
                ('movies', models.ManyToManyField(to='items.Movie')),
            ],
        ),
    ]
