# Generated by Django 2.0.5 on 2018-11-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0045_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='poster',
            field=models.ImageField(blank=True, upload_to='Topic/'),
        ),
        migrations.AddField(
            model_name='video',
            name='related_topics',
            field=models.ManyToManyField(blank=True, related_name='videos', to='items.Topic'),
        ),
    ]
