# Generated by Django 2.0.5 on 2018-11-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0022_profile_follow_lists'),
        ('items', '0046_auto_20181117_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('abstract', models.CharField(blank=True, max_length=10000, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('related_movies', models.ManyToManyField(blank=True, related_name='articles', to='items.Movie')),
                ('related_persons', models.ManyToManyField(blank=True, related_name='articles', to='persons.Person')),
                ('related_topics', models.ManyToManyField(blank=True, related_name='articles', to='items.Topic')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
