# Generated by Django 2.0.5 on 2018-11-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0049_auto_20181117_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
