# Generated by Django 2.0.5 on 2018-11-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0022_profile_follow_lists'),
        ('items', '0050_auto_20181117_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='persons',
            field=models.ManyToManyField(to='persons.Person'),
        ),
    ]
