# Generated by Django 2.0.5 on 2018-11-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0051_topic_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='lists',
            field=models.ManyToManyField(blank=True, null=True, related_name='topics', to='items.List'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='topics', to='items.Movie'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='persons',
            field=models.ManyToManyField(blank=True, null=True, related_name='topics', to='persons.Person'),
        ),
    ]
