# Generated by Django 2.0.5 on 2018-11-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0054_auto_20181121_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-year']},
        ),
        migrations.AlterField(
            model_name='list',
            name='movies',
            field=models.ManyToManyField(related_name='lists', to='items.Movie'),
        ),
    ]
