# Generated by Django 2.0.5 on 2018-11-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0055_auto_20181125_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='priority',
        ),
        migrations.AddField(
            model_name='list',
            name='priority',
            field=models.IntegerField(blank=True, help_text='Give different priority number for each movie, in order to get sorting.', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
