# Generated by Django 2.0.5 on 2018-12-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0025_person_active'),
        ('items', '0060_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='acted', to='persons.Person'),
        ),
    ]
