# Generated by Django 2.0.5 on 2018-12-04 20:51

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0061_auto_20181203_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to=items.models.movie_poster_upload_path),
        ),
    ]
