# Generated by Django 2.0.5 on 2018-12-05 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0031_auto_20181205_2149'),
        ('items', '0062_auto_20181204_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='editor',
            field=models.ManyToManyField(related_name='edited', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='photography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photographed', to='persons.Person'),
        ),
    ]
