# Generated by Django 2.0.5 on 2018-12-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0064_auto_20181206_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='dop',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='editors',
        ),
    ]
