# Generated by Django 2.0.5 on 2018-12-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0032_crew'),
        ('items', '0065_auto_20181206_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='people',
            field=models.ManyToManyField(through='persons.Crew', to='persons.Person'),
        ),
    ]
