# Generated by Django 2.0.5 on 2018-12-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0066_movie_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='people',
            field=models.ManyToManyField(blank=True, null=True, through='persons.Crew', to='persons.Person'),
        ),
    ]
