# Generated by Django 2.0.5 on 2019-01-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0067_auto_20181209_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='Thumbnail url if exists.', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Youtube video id, if video is on TouTube.', max_length=50, null=True),
        ),
    ]
