# Generated by Django 2.0.5 on 2019-01-21 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0043_auto_20190121_1735'),
        ('items', '0068_auto_20190102_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='priority',
        ),
        migrations.AddField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lists', to='persons.Profile'),
        ),
        migrations.AddField(
            model_name='list',
            name='reference_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='reference_notes',
            field=models.CharField(blank=True, help_text='Notes about reference.', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='related_persons',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_lists', to='persons.Person'),
        ),
    ]
