# Generated by Django 2.0.5 on 2019-01-21 22:27

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0070_list_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='priority',
            field=django_mysql.models.ListTextField(models.IntegerField(), blank=True, default=[], help_text='Add movie ids in order. Movies will display in this order. ', max_length=150, null=True, size=None),
        ),
    ]
