# Generated by Django 2.0.5 on 2019-01-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0071_auto_20190122_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='priority',
        ),
    ]
