# Generated by Django 2.0.5 on 2019-01-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0072_remove_list_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='reference_link',
            field=models.URLField(blank=True, help_text='Reference of relation with person. Enter link of url', null=True),
        ),
    ]
