# Generated by Django 2.0.5 on 2019-01-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0075_auto_20190122_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('df', "Director's Favourite")], help_text="What is the relation about the list and person? E.g; 'Directors favourite movie list'", max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
