# Generated by Django 2.0.5 on 2019-01-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0076_auto_20190126_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('f', "Director's Favourite")], help_text="What is the relation about the list and person? E.g; 'Directors favourite movie list'", max_length=1, null=True),
        ),
    ]
