# Generated by Django 2.0.5 on 2019-01-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0077_auto_20190126_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='list',
            name='list_type',
            field=models.CharField(blank=True, choices=[('df', "Director's Favourite")], help_text="What is the relation about the list and person? E.g; 'Directors favourite movie list'", max_length=3, null=True),
        ),
    ]
