# Generated by Django 2.0.5 on 2019-01-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0078_auto_20190130_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_type',
            field=models.CharField(blank=True, choices=[('df', "Director's Favourite"), ('fw', 'Festival Winner Movies')], help_text="What is the relation about the list and person? E.g; 'Directors favourite movie list'", max_length=3, null=True),
        ),
    ]
