# Generated by Django 2.0.5 on 2019-01-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0079_auto_20190130_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='people',
        ),
        migrations.AlterField(
            model_name='list',
            name='movies',
            field=models.ManyToManyField(related_name='lists', to='items.Movie'),
        ),
        migrations.AlterField(
            model_name='list',
            name='related_persons',
            field=models.ManyToManyField(related_name='related_lists', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='lists',
            field=models.ManyToManyField(related_name='topics', to='items.List'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='movies',
            field=models.ManyToManyField(related_name='topics', to='items.Movie'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='persons',
            field=models.ManyToManyField(related_name='topics', to='persons.Person'),
        ),
    ]
