# Generated by Django 2.0.5 on 2019-02-20 16:13

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0081_auto_20190208_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_poster',
            field=models.ImageField(blank=True, upload_to=items.models.movie_cover_poster_upload_path),
        ),
    ]
