# Generated by Django 2.0.5 on 2019-03-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0082_movie_cover_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='related_persons',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_lists', to='persons.Person'),
        ),
    ]
