# Generated by Django 2.0.5 on 2019-03-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0083_auto_20190304_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_type',
            field=models.CharField(blank=True, choices=[('df', "Director's Favourite"), ('fw', 'Festival Winner Movies'), ('gr', 'Genre Related')], help_text="What is the relation about the list and person? E.g; 'Directors favourite movie list'", max_length=3, null=True),
        ),
    ]
