# Generated by Django 2.0.5 on 2019-03-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0084_auto_20190304_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_type',
            field=models.CharField(blank=True, choices=[('df', "Director's Favourite"), ('fw', 'Festival Winner Movies'), ('gr', 'Genre Related'), ('ms', 'Miscellaneous')], help_text="What is the relation about the list and person? E.g; 'Directors favourite movie list'", max_length=3, null=True),
        ),
    ]
