# Generated by Django 2.0.5 on 2019-03-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0085_auto_20190304_0227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prediction',
            options={'ordering': ['-created_at']},
        ),
    ]
