# Generated by Django 2.0.5 on 2019-06-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0086_auto_20190312_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Youtube video id, if video is on TouTube.', max_length=50, null=True, unique=True),
        ),
    ]
