# Generated by Django 2.0.5 on 2019-06-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0087_auto_20190604_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
