# Generated by Django 2.0.5 on 2019-06-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0089_movie_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('movielens_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tags',
        ),
        migrations.AddField(
            model_name='tags',
            name='related_movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='items.Movie'),
        ),
    ]
