# Generated by Django 2.0.5 on 2019-06-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0090_auto_20190612_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
    ]
