# Generated by Django 2.0.5 on 2019-06-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0091_remove_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='related_topics',
        ),
        migrations.AddField(
            model_name='video',
            name='related_lists',
            field=models.ManyToManyField(blank=True, related_name='videos', to='items.List'),
        ),
    ]
