# Generated by Django 2.2 on 2019-06-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0092_auto_20190612_1828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
