# Generated by Django 2.2 on 2019-06-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0093_delete_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('movielens_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('related_movies', models.ManyToManyField(blank=True, null=True, related_name='tags', to='items.Movie')),
            ],
        ),
    ]
