# Generated by Django 2.0.5 on 2019-06-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0095_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(blank=True, choices=[('based', 'Based on'), ('city', 'Festival Winner Movies'), ('county', 'Genre Related'), ('genre', 'Miscellaneous')], max_length=11, null=True),
        ),
    ]
