# Generated by Django 2.0.5 on 2019-06-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0099_auto_20190613_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(blank=True, choices=[('award', 'Awarded'), ('base', 'Based on'), ('city', 'Cities'), ('content', 'Content'), ('country', 'Country'), ('genre', 'Genre'), ('era', 'Era movie')], max_length=11, null=True),
        ),
    ]
