# Generated by Django 2.0.5 on 2019-06-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0100_auto_20190613_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='custom_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
