# Generated by Django 2.0.5 on 2019-06-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0101_tag_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
