# Generated by Django 2.0.5 on 2019-06-13 10:51

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0102_tag_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=items.models.tag_image_upload_path),
        ),
    ]
