# Generated by Django 2.0.5 on 2019-06-13 12:07

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0103_tag_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=items.models.list_image_upload_path),
        ),
    ]
