# Generated by Django 2.0.5 on 2019-06-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0104_list_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='discipline_type',
            field=models.CharField(blank=True, choices=[('award', 'Awarded'), ('base', 'Based on'), ('city', 'Cities'), ('content', 'Content'), ('country', 'Country'), ('genre', 'Genre'), ('era', 'Era movie')], max_length=11, null=True),
        ),
    ]
