# Generated by Django 2.0.5 on 2019-06-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0105_tag_discipline_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_lists', to='items.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='discipline_type',
            field=models.CharField(blank=True, choices=[('phil', 'Philosophy'), ('soc', 'Sociology'), ('psy', 'Psychology')], max_length=11, null=True),
        ),
    ]
