# Generated by Django 2.0.5 on 2019-06-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0106_auto_20190625_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='related_lists',
        ),
    ]
