# Generated by Django 2.0.5 on 2019-06-25 18:38

from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0067_auto_20190603_2013'),
        ('items', '0107_remove_video_related_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True, max_length=2000, null=True)),
                ('public', models.BooleanField(default=True)),
                ('reference_notes', models.CharField(blank=True, help_text='Notes about reference.', max_length=400, null=True)),
                ('reference_link', models.URLField(blank=True, help_text='Reference: Enter link of url', null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to=items.models.video_image_upload_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_lists', to='persons.Profile')),
                ('related_persons', models.ManyToManyField(blank=True, null=True, related_name='related_video_lists', to='persons.Person')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='related_video_lists', to='items.Tag')),
                ('videos', models.ManyToManyField(related_name='related_lists', to='items.Video')),
            ],
        ),
    ]
