# Generated by Django 2.0.5 on 2019-07-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0108_videolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
