# Generated by Django 2.0.5 on 2019-08-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0110_auto_20190729_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
