# Generated by Django 2.0.5 on 2019-08-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0111_auto_20190808_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
