# Generated by Django 2.0.5 on 2019-08-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0113_auto_20190809_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='summary',
            field=models.TextField(blank=True, help_text='Minimumun 250 character, otherwise will not be shown.', max_length=1000, null=True),
        ),
    ]
