# Generated by Django 2.0.5 on 2019-08-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0117_auto_20190815_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
