# Generated by Django 2.0.5 on 2019-08-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0118_auto_20190817_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieimage',
            name='movie',
        ),
        migrations.DeleteModel(
            name='MovieImage',
        ),
    ]
