# Generated by Django 2.0.5 on 2019-08-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0120_tag_object_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='tags',
            new_name='tagss',
        ),
        migrations.AddField(
            model_name='tag',
            name='related_videos',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='items.Video'),
        ),
    ]
