# Generated by Django 2.0.5 on 2019-08-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0121_auto_20190818_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='related_lists',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='items.List'),
        ),
    ]
