# Generated by Django 2.0.5 on 2019-08-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0122_auto_20190819_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='related_lists',
        ),
    ]
