# Generated by Django 2.0.5 on 2019-08-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0123_remove_tag_related_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='related_lists',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='items.List'),
        ),
    ]
