# Generated by Django 2.0.5 on 2019-08-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0124_tag_related_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='quantity',
        ),
    ]
