# Generated by Django 2.0.5 on 2019-08-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0125_remove_tag_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='object_type',
            field=models.CharField(blank=True, choices=[('movie', 'Movie Content Tags'), ('video', 'Video Content Tags'), ('list', 'List Content Tags'), ('article', 'Article/Blog Post Tags')], max_length=11, null=True),
        ),
    ]
