# Generated by Django 2.0.5 on 2019-08-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0128_auto_20190820_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='wiki',
            field=models.URLField(blank=True, null=True),
        ),
    ]
