# Generated by Django 2.0.5 on 2019-08-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0129_movie_wiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='rich_data',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rich_data',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
