# Generated by Django 2.0.5 on 2019-08-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0130_auto_20190820_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='rich_data',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rich_data',
        ),
    ]
