# Generated by Django 2.0.5 on 2019-08-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0132_auto_20190820_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='rich_data',
            new_name='richdata',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='rich_data',
            new_name='richdata',
        ),
    ]
