# Generated by Django 2.0.5 on 2019-08-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0133_auto_20190820_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='videolist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
