# Generated by Django 2.0.5 on 2019-08-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0134_auto_20190821_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
