# Generated by Django 2.0.5 on 2019-08-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0136_tag_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(blank=True, choices=[('award', 'Awarded'), ('base', 'Based on'), ('tag', 'Content-Tag'), ('country', 'Country'), ('genre', 'Genre'), ('era', 'Era movie')], max_length=11, null=True),
        ),
    ]
