# Generated by Django 2.0.5 on 2019-08-28 11:41

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0086_auto_20190820_2224'),
        ('items', '0138_auto_20190827_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(max_length=2000)),
                ('reference_notes', models.CharField(blank=True, help_text='Notes about reference.', max_length=400, null=True)),
                ('reference_link', models.URLField(blank=True, help_text='Reference of relation with person. Enter link of url', null=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='items.Movie')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='persons.Person')),
            ],
        ),
    ]
