# Generated by Django 2.0.5 on 2019-08-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0139_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
