# Generated by Django 2.0.5 on 2019-08-29 23:27

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0140_auto_20190828_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='data',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
