# Generated by Django 2.0.5 on 2019-08-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0141_video_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tmdb_id_2',
            field=models.IntegerField(blank=True, help_text="in case of similar tags like: 'heartwarming' and 'heart-warming'", null=True, unique=True),
        ),
    ]
