# Generated by Django 2.0.5 on 2019-08-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0142_tag_tmdb_id_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(blank=True, choices=[('award', 'Awarded'), ('base', 'Based on'), ('content', 'Content-Tag'), ('country', 'Country'), ('genre', 'Genre'), ('subgenre', 'Sub-Genre'), ('era', 'Era movie')], max_length=11, null=True),
        ),
    ]
