# Generated by Django 2.0.5 on 2019-08-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0144_auto_20190830_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='historical_person_tag',
            field=models.BooleanField(default=False),
        ),
    ]
