# Generated by Django 2.0.5 on 2019-08-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0145_tag_historical_person_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='video_tag',
            field=models.BooleanField(default=False, help_text='tags that classifies video object'),
        ),
    ]
