# Generated by Django 2.0.5 on 2019-08-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0146_auto_20190830_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='phenomenal_tag',
            field=models.BooleanField(default=False),
        ),
    ]
