# Generated by Django 2.0.5 on 2019-08-30 16:22

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0147_tag_phenomenal_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='parent_genres',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), blank=True, default=[], help_text='list of parent-genres slugs', null=True, size=None),
        ),
    ]
