# Generated by Django 2.0.5 on 2019-08-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0148_auto_20190830_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='documentary_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='series_tag',
            field=models.BooleanField(default=False),
        ),
    ]
