# Generated by Django 2.0.5 on 2019-08-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0150_tag_form_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='netflix_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
