# Generated by Django 2.0.5 on 2019-08-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0151_tag_netflix_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='topic_tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='theme_tag',
            field=models.BooleanField(default=False, help_text='Narrow topics, or more special cases; suicide-attempt, surf, prison-escape'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='form_tag',
            field=models.BooleanField(default=False, help_text='About form of movie; no-dialogue, dialogue, 70mm, nonlinear, multiple-storylines, etc..'),
        ),
    ]
