# Generated by Django 2.0.5 on 2019-09-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0152_auto_20190831_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(related_name='topics', to='items.Tag'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, help_text='Detailed description', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='summary',
            field=models.TextField(blank=True, help_text='short summary of topic', max_length=300, null=True),
        ),
    ]
