# Generated by Django 2.0.5 on 2019-09-01 15:28

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0153_auto_20190901_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='richdata',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='seo_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='seo_keywords',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='seo_short_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='seo_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
