# Generated by Django 2.0.5 on 2019-09-01 15:29

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0154_auto_20190901_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='cover_poster',
            field=models.ImageField(blank=True, upload_to=items.models.topic_cover_poster_upload_path),
        ),
    ]
