# Generated by Django 2.0.5 on 2019-09-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0155_topic_cover_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
