# Generated by Django 2.0.5 on 2019-09-02 16:44

from django.db import migrations, models
import django_mysql.models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0086_auto_20190820_2224'),
        ('items', '0156_topic_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('seo_title', models.CharField(blank=True, max_length=100, null=True)),
                ('seo_short_description', models.TextField(blank=True, max_length=500, null=True)),
                ('seo_description', models.TextField(blank=True, max_length=500, null=True)),
                ('seo_keywords', models.TextField(blank=True, max_length=2000, null=True)),
                ('richdata', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='list',
            name='cover_poster',
            field=models.ImageField(blank=True, null=True, upload_to=items.models.list_image_upload_path),
        ),
        migrations.AlterField(
            model_name='topic',
            name='lists',
            field=models.ManyToManyField(blank=True, null=True, related_name='topics', to='items.List'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='topics', to='items.Movie'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='persons',
            field=models.ManyToManyField(blank=True, null=True, related_name='topics', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='topics', to='items.Tag'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='lists',
            field=models.ManyToManyField(blank=True, null=True, to='items.List'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='items.Movie'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='persons',
            field=models.ManyToManyField(blank=True, null=True, to='persons.Person'),
        ),
    ]
