# Generated by Django 2.0.5 on 2019-09-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0157_auto_20190902_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='lists',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='persons',
        ),
        migrations.DeleteModel(
            name='MainPage',
        ),
    ]
