# Generated by Django 2.0.5 on 2019-09-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0158_auto_20190902_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='main_page',
            field=models.BooleanField(default=False, help_text='Selected item will be showed on welcome screen'),
        ),
        migrations.AddField(
            model_name='movie',
            name='main_page',
            field=models.BooleanField(default=False, help_text='Selected item will be showed on welcome screen'),
        ),
    ]
