# Generated by Django 2.0.5 on 2019-09-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0159_auto_20190902_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='adult_tag',
            field=models.BooleanField(default=False),
        ),
    ]
