# Generated by Django 2.0.5 on 2019-10-11 15:59

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0160_tag_adult_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='order',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
