# Generated by Django 2.0.5 on 2019-10-11 16:04

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0161_list_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='order',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
