# Generated by Django 2.0.5 on 2019-10-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0163_list_large_cover_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
