# Generated by Django 2.0.5 on 2019-10-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0165_tag_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='summary',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
