# Generated by Django 2.0.5 on 2019-10-16 00:01

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0166_auto_20191015_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='data',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
