# Generated by Django 2.0.5 on 2019-10-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0167_auto_20191016_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='topic_tag',
            field=models.BooleanField(default=False),
        ),
    ]
