# Generated by Django 2.0.5 on 2019-10-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0169_auto_20191016_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='main_page',
        ),
        migrations.AddField(
            model_name='tag',
            name='main_page',
            field=models.BooleanField(default=False, help_text='Selected item will be showed on welcome screen'),
        ),
    ]
