# Generated by Django 2.0.5 on 2019-10-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0170_auto_20191016_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='main_page',
            field=models.BooleanField(default=False, help_text='Selected item will be showed on welcome screen'),
        ),
    ]
