# Generated by Django 2.0.5 on 2019-10-16 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0172_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Tag'),
        ),
    ]
