# Generated by Django 2.0.5 on 2019-10-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0173_topic_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='quotes',
            field=models.ManyToManyField(blank=True, null=True, related_name='topics', to='items.Quote'),
        ),
    ]
