# Generated by Django 2.0.5 on 2019-10-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0174_topic_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='owner_text',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
