# Generated by Django 2.0.5 on 2019-10-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0175_quote_owner_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='owner_text',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='owner',
            new_name='person',
        ),
    ]
