# Generated by Django 2.0.5 on 2019-10-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0176_auto_20191017_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='active',
        ),
    ]
