# Generated by Django 2.0.5 on 2019-11-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0179_topic_wiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='searchable',
            field=models.BooleanField(default=True),
        ),
    ]
