# Generated by Django 2.0.5 on 2019-11-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0182_auto_20191109_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='searchable',
            field=models.BooleanField(default=False, help_text='Allows year and rating filtering. If there are many movies, select this.'),
        ),
    ]
