# Generated by Django 2.0.5 on 2019-11-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0183_auto_20191109_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='html_content',
        ),
    ]
