# Generated by Django 2.0.5 on 2019-11-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0184_remove_topic_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_article',
            field=models.BooleanField(default=False, help_text='If the content is rich enough select this.'),
        ),
    ]
