# Generated by Django 2.0.5 on 2019-11-23 22:30

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0189_auto_20191116_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='large_poster',
            field=models.ImageField(blank=True, upload_to=items.models.movie_large_poster_upload_path),
        ),
    ]
