# Generated by Django 2.0.5 on 2019-11-30 20:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0190_movie_large_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed description', max_length=10000, null=True),
        ),
    ]
