# Generated by Django 2.0.5 on 2019-11-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0192_auto_20191130_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
