# Generated by Django 2.0.5 on 2019-12-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0194_auto_20191201_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
