# Generated by Django 2.0.5 on 2019-12-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0195_auto_20191204_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='is_published',
            field=models.BooleanField(default=False, help_text='True for RSS publishing, leave it False if you are unsure'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_published',
            field=models.BooleanField(default=False, help_text='True for RSS publishing, leave it False if you are unsure'),
        ),
    ]
