# Generated by Django 2.0.5 on 2019-12-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0196_auto_20191207_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='is_newest',
            field=models.BooleanField(default=False, help_text='True for displaying in the latest section'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_newest',
            field=models.BooleanField(default=False, help_text='True for displaying in the latest section'),
        ),
        migrations.AlterField(
            model_name='list',
            name='list_type',
            field=models.CharField(blank=True, choices=[('df', "Director's Favourite"), ('fw', 'Festival Winner Movies'), ('gr', 'Genre Related'), ('ms', 'Miscellaneous'), ('mm', 'Movies of the Month'), ('my', 'Movies of the Year')], help_text="What is the relation about the list and person? E.g; 'Directors favourite movie list'", max_length=3, null=True),
        ),
    ]
