# Generated by Django 2.0.5 on 2019-12-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0104_auto_20191116_1622'),
        ('items', '0198_oscars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oscars',
            new_name='Oscar',
        ),
    ]
