# Generated by Django 2.0.5 on 2019-12-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0199_auto_20191221_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oscar',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='oscars', to='items.Movie'),
        ),
        migrations.AlterField(
            model_name='oscar',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
