# Generated by Django 2.0.5 on 2019-12-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0200_auto_20191221_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oscar',
            name='movie',
            field=models.ForeignKey(help_text="winner of the award's movie.", on_delete=django.db.models.deletion.CASCADE, related_name='oscars_won', to='items.Movie'),
        ),
        migrations.AlterField(
            model_name='oscar',
            name='movies',
            field=models.ManyToManyField(blank=True, help_text='Nominees. If the award is personal award leave it blank', null=True, related_name='oscars', to='items.Movie'),
        ),
    ]
