# Generated by Django 2.0.5 on 2019-12-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0201_auto_20191221_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oscar',
            name='movies',
            field=models.ManyToManyField(blank=True, help_text='Nominees. If the award is personal set movies that the person play in.', null=True, related_name='oscars', to='items.Movie'),
        ),
    ]
