# Generated by Django 2.0.5 on 2019-12-21 19:22

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0204_auto_20191221_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='topic_poster',
            field=models.ImageField(blank=True, upload_to=items.models.movie_topic_poster_upload_path),
        ),
    ]
