# Generated by Django 2.0.5 on 2019-12-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0206_auto_20191221_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='topic_poster',
            new_name='wide_poster',
        ),
    ]
