# Generated by Django 2.0.5 on 2019-12-22 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0207_auto_20191222_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='movie',
            field=models.ForeignKey(help_text="winner of the award's movie.", on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='items.Movie'),
        ),
        migrations.AlterField(
            model_name='award',
            name='movies',
            field=models.ManyToManyField(blank=True, help_text='Nominees. If the award is personal set movies that the person play in.', null=True, related_name='awards_nominee', to='items.Movie'),
        ),
        migrations.AlterField(
            model_name='award',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='persons.Person'),
        ),
        migrations.AlterField(
            model_name='award',
            name='persons',
            field=models.ManyToManyField(blank=True, null=True, related_name='awards_nominee', to='persons.Person'),
        ),
    ]
