# Generated by Django 2.0.5 on 2019-12-23 13:41

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0208_auto_20191222_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='hero_poster',
            field=models.ImageField(blank=True, upload_to=items.models.topic_hero_poster_upload_path),
        ),
    ]
