# Generated by Django 2.0.5 on 2020-01-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0210_auto_20191226_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
