# Generated by Django 2.0.5 on 2020-01-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0211_auto_20200108_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='content_similars_summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
