# Generated by Django 2.0.5 on 2020-01-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0212_movie_content_similars_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='short_name',
            field=models.CharField(blank=True, help_text="This will be used in a situation that requires short name rather than 'The Best ....'", max_length=50, null=True),
        ),
    ]
