# Generated by Django 2.0.5 on 2020-01-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0213_topic_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='important_page',
            field=models.BooleanField(default=False, help_text='Selected item page can be allowed make dofollow links.'),
        ),
        migrations.AddField(
            model_name='movie',
            name='important_page',
            field=models.BooleanField(default=False, help_text='Selected item page can be allowed make dofollow links.'),
        ),
        migrations.AddField(
            model_name='tag',
            name='important_page',
            field=models.BooleanField(default=False, help_text='Selected item page can be allowed make dofollow links.'),
        ),
        migrations.AddField(
            model_name='topic',
            name='important_page',
            field=models.BooleanField(default=False, help_text='Selected item page can be allowed make dofollow links.'),
        ),
    ]
