# Generated by Django 2.0.5 on 2020-01-15 14:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0214_auto_20200110_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='references',
            field=ckeditor.fields.RichTextField(blank=True, help_text='References at the bottom of the page', max_length=1000, null=True),
        ),
    ]
