# Generated by Django 2.0.5 on 2020-01-20 11:54

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0215_topic_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_ordered',
            field=models.BooleanField(default=False, help_text='True for ordered content display.(default=False)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='movie_order',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), blank=True, default=[], help_text='Ordered movie slugs: the movies and its content will display according to this order.', null=True, size=None),
        ),
    ]
