# Generated by Django 2.0.5 on 2020-01-21 12:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0217_auto_20200120_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=80, null=True)),
                ('summary', models.TextField(blank=True, help_text='short summary of topic. max: 300 characters', max_length=300, null=True)),
                ('html_content', ckeditor.fields.RichTextField(blank=True, help_text='Detailed description', max_length=50000, null=True)),
                ('references', ckeditor.fields.RichTextField(blank=True, help_text='References at the bottom of the page', max_length=1000, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_items', to='items.Movie')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_items', to='items.Topic')),
            ],
        ),
    ]
