# Generated by Django 2.0.5 on 2020-01-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0218_topicitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='feature_movies',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='lists',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='movie_order',
        ),
    ]
