# Generated by Django 2.0.5 on 2020-01-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0220_auto_20200121_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicitems',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='topicitems',
            name='topic',
        ),
        migrations.DeleteModel(
            name='TopicItems',
        ),
    ]
