# Generated by Django 2.0.5 on 2020-01-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0222_topicitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicitems',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
