# Generated by Django 2.0.5 on 2020-01-21 14:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0224_auto_20200121_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('header', models.CharField(blank=True, help_text='In case of different text, use this as header', max_length=80, null=True)),
                ('html_content', ckeditor.fields.RichTextField(blank=True, help_text='Detailed description', max_length=10000, null=True)),
                ('references', ckeditor.fields.RichTextField(blank=True, help_text='References at the bottom of the page', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_topics', to='items.Movie')),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='movies',
            field=models.ManyToManyField(blank=True, help_text='Leave blank if is_ordered=True', null=True, related_name='topics', to='items.Movie'),
        ),
        migrations.AddField(
            model_name='topicitem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.Topic'),
        ),
    ]
