# Generated by Django 2.0.5 on 2020-01-21 22:31

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0226_topicitem_cover_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicitem',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=items.models.topic_item_poster_path),
        ),
    ]
