# Generated by Django 2.0.5 on 2020-01-23 17:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0227_topicitem_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='html_content2',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed description', max_length=10000, null=True),
        ),
    ]
