# Generated by Django 2.0.5 on 2020-01-23 23:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0228_topic_html_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='show_html_content2',
            field=models.BooleanField(default=True, help_text='For mobile hiding of the text.'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='html_content2',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Second part of detailed description', max_length=10000, null=True),
        ),
    ]
