# Generated by Django 2.0.5 on 2020-01-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0105_person_important_page'),
        ('items', '0229_auto_20200124_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicitem',
            name='persons',
            field=models.ManyToManyField(blank=True, null=True, related_name='topic_items', to='persons.Person'),
        ),
    ]
