# Generated by Django 2.0.5 on 2020-01-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0230_topicitem_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicitem',
            name='rank',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
