# Generated by Django 2.0.5 on 2020-01-24 13:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0231_auto_20200124_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='html_content3',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Final part of detailed description, use for last senteces, or if html_content2 is not visible.', max_length=1000, null=True),
        ),
    ]
