# Generated by Django 2.0.5 on 2020-01-24 14:19

import ckeditor.fields
from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0106_auto_20200124_0332'),
        ('items', '0232_topic_html_content3'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(blank=True, help_text='In case of different text, use this as header', max_length=80, null=True)),
                ('html_content', ckeditor.fields.RichTextField(blank=True, help_text='Detailed description', max_length=10000, null=True)),
                ('cover_poster', models.ImageField(blank=True, null=True, upload_to=items.models.movie_group_cover_path)),
                ('poster', models.ImageField(blank=True, null=True, upload_to=items.models.movie_group_poster_path)),
                ('references', ckeditor.fields.RichTextField(blank=True, help_text='References at the bottom of the page', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('movies', models.ManyToManyField(blank=True, null=True, related_name='groups', to='persons.Person')),
                ('topic', models.ManyToManyField(related_name='groups', to='items.Topic')),
            ],
        ),
    ]
