# Generated by Django 2.0.5 on 2020-01-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0233_moviegroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviegroup',
            old_name='topic',
            new_name='topics',
        ),
    ]
