# Generated by Django 2.0.5 on 2020-01-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0234_auto_20200124_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegroup',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='items.Movie'),
        ),
    ]
