# Generated by Django 2.0.5 on 2020-01-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0235_auto_20200124_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviegroup',
            name='references',
        ),
        migrations.AlterField(
            model_name='moviegroup',
            name='name',
            field=models.CharField(blank=True, help_text='Name', max_length=80, null=True),
        ),
    ]
