# Generated by Django 2.0.5 on 2020-01-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0236_auto_20200124_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegroup',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='items.Topic'),
        ),
    ]
