# Generated by Django 2.0.5 on 2020-01-24 16:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0238_auto_20200124_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviegroup',
            old_name='name',
            new_name='header',
        ),
        migrations.RemoveField(
            model_name='moviegroupitem',
            name='name',
        ),
        migrations.AddField(
            model_name='moviegroup',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='items.Topic'),
        ),
        migrations.AddField(
            model_name='moviegroupitem',
            name='header',
            field=models.CharField(blank=True, help_text='Unque name, in case of attractive header', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='moviegroup',
            name='html_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Description for all the movies and topic. In movie page, movie group item's description will be used not this.", max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='moviegroupitem',
            name='html_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed description of the item. Use similar bu unique description for each item in the group', max_length=1000, null=True),
        ),
    ]
