# Generated by Django 2.0.5 on 2020-01-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0240_auto_20200124_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviegroup',
            name='poster_type',
            field=models.CharField(choices=[('df', "Director's Favourite"), ('fw', 'Festival Winner Movies'), ('gr', 'Genre Related'), ('ms', 'Miscellaneous'), ('mm', 'Movies of the Month'), ('my', 'Movies of the Year')], default='cover', max_length=5),
        ),
    ]
