# Generated by Django 2.0.5 on 2020-01-29 17:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0246_moviegroup_have_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='html_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Description for all the movies and topic. In mov', max_length=10000, null=True),
        ),
    ]
