# Generated by Django 2.0.5 on 2020-01-29 18:15

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0247_list_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegroup',
            name='cover_poster',
            field=models.ImageField(blank=True, help_text='600x338px', null=True, upload_to=items.models.movie_group_cover_path),
        ),
    ]
