# Generated by Django 2.0.5 on 2020-01-29 18:19

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0248_auto_20200129_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviegroup',
            name='important_page',
            field=models.BooleanField(default=False, help_text='Selected item page can be allowed make dofollow links.'),
        ),
        migrations.AddField(
            model_name='moviegroup',
            name='main_page',
            field=models.BooleanField(default=False, help_text='Selected item will be showed on welcome screen'),
        ),
        migrations.AddField(
            model_name='moviegroup',
            name='richdata',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='moviegroup',
            name='seo_description',
            field=models.TextField(blank=True, help_text='160 character limit', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='moviegroup',
            name='seo_keywords',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='moviegroup',
            name='seo_short_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='moviegroup',
            name='seo_title',
            field=models.CharField(blank=True, help_text='70 character limit. 65 is OK', max_length=70, null=True),
        ),
    ]
