# Generated by Django 2.0.5 on 2020-01-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0249_auto_20200129_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegroup',
            name='have_page',
            field=models.BooleanField(default=False, help_text='if yes, group treated like list or topic and have unique url'),
        ),
    ]
