# Generated by Django 2.0.5 on 2020-02-17 17:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0250_auto_20200129_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='html_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='For Feature Movies that will show on Topic Page.', max_length=10000, null=True),
        ),
    ]
