# Generated by Django 2.0.5 on 2020-02-17 22:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0106_auto_20200124_0332'),
        ('items', '0251_auto_20200217_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', ckeditor.fields.RichTextField(blank=True, help_text='Both Blocquote and the owner of critic and else.', max_length=10000, null=True)),
                ('critic', models.TextField(blank=True, help_text='for database query and other differentiations. Write everything including critic to html_content.', max_length=100, null=True)),
                ('reference_notes', models.CharField(blank=True, help_text='Notes about reference.', max_length=400, null=True)),
                ('reference_link', models.URLField(blank=True, help_text='Reference of relation with person. Enter link of url', null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='items.Movie')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='persons.Person')),
            ],
        ),
    ]
