# Generated by Django 2.0.5 on 2020-02-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0252_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='critic',
            field=models.CharField(blank=True, help_text='for database query and other differentiations. Write everything including critic to html_content.', max_length=100, null=True),
        ),
    ]
