# Generated by Django 2.0.5 on 2020-02-18 01:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0253_auto_20200218_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(default='default', help_text='Quote with quotation mark.', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='html_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='The owner of review and related info.', max_length=10000, null=True),
        ),
    ]
