# Generated by Django 2.0.5 on 2020-02-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0254_auto_20200218_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='primary',
            field=models.BooleanField(default=False, help_text='Use this for featured review'),
        ),
    ]
