# Generated by Django 2.0.5 on 2020-02-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0255_review_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(help_text='Quote without quotation mark.', max_length=2000),
        ),
    ]
