# Generated by Django 2.0.5 on 2020-02-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0256_auto_20200218_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='header',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
