# Generated by Django 2.0.5 on 2020-04-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0260_auto_20200308_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='free_watch_link',
            field=models.URLField(blank=True, help_text='if a movie can be watch freely, give the address', null=True),
        ),
    ]
