# Generated by Django 2.0.5 on 2019-09-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(default='...', editable=False, max_length=5000),
        ),
    ]
