# Generated by Django 2.0.5 on 2019-09-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixly', '0002_auto_20190907_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='person',
            new_name='profile',
        ),
    ]
