# Generated by Django 2.0.5 on 2019-09-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixly', '0003_auto_20190907_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ip',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
