# Generated by Django 2.0.5 on 2020-03-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixly', '0005_auto_20190907_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
