# Generated by Django 2.0.5 on 2020-03-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixly', '0006_auto_20200306_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='_message',
            field=models.CharField(default='...', editable=False, max_length=5000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(default='...', max_length=5000),
        ),
    ]
