# Generated by Django 2.0.5 on 2019-04-15 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0005_auto_20190208_1621'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ratings', django_mysql.models.JSONField(default=dict)),
                ('similars_dummy', django_mysql.models.JSONField(default=dict)),
                ('similars_real', django_mysql.models.JSONField(default=dict)),
                ('ua', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.UserArchive', verbose_name='archive')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
