# Generated by Django 2.0.5 on 2019-04-17 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='ua',
        ),
    ]
