# Generated by Django 2.0.5 on 2019-04-18 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20190418_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='user',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
