# Generated by Django 2.0.5 on 2019-04-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
