# Generated by Django 2.0.5 on 2019-04-29 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0057_logentry'),
        ('items', '0086_auto_20190312_2040'),
        ('persona', '0009_auto_20190429_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('prediction', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('recommended_at', models.DateTimeField(null=True)),
                ('is_watched', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField(null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.Movie')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recommendations', to='persons.Profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
