# Generated by Django 2.0.5 on 2019-04-29 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0010_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Movie'),
        ),
    ]
