# Generated by Django 2.0.5 on 2020-03-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0011_auto_20190430_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='rec_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
