# Generated by Django 2.0.5 on 2019-12-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='page_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
