# Generated by Django 2.0.5 on 2019-12-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_feedpost_page_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='xml_content',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
