# Generated by Django 2.0.5 on 2019-12-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_feedpost_xml_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpost',
            name='movies',
        ),
        migrations.DeleteModel(
            name='FeedPost',
        ),
    ]
