# Generated by Django 2.0.5 on 2019-12-07 17:06

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0196_auto_20191207_2006'),
        ('feed', '0006_auto_20191207_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=400)),
                ('link', models.URLField(blank=True, null=True)),
                ('page_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='It should generally contain 300 or more characters to provide an attractive, informative summary. ', max_length=300, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('xml_content', models.TextField(blank=True, max_length=50000, null=True)),
                ('creator', models.CharField(blank=True, max_length=400, null=True)),
                ('poster', models.ImageField(blank=True, upload_to=feed.models.vertical_upload_path)),
                ('cover_poster', models.ImageField(blank=True, upload_to=feed.models.horizontal_upload_path)),
                ('is_published', models.BooleanField(default=False)),
                ('movies', models.ManyToManyField(blank=True, null=True, related_name='parent_feeds', to='items.Movie')),
            ],
        ),
    ]
