# Generated by Django 2.0.5 on 2019-12-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_feedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpost',
            name='liste',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='topic',
        ),
        migrations.DeleteModel(
            name='FeedPost',
        ),
    ]
