# Generated by Django 2.0.5 on 2019-12-07 17:51

from django.db import migrations, models
import django.db.models.deletion
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0196_auto_20191207_2006'),
        ('feed', '0011_feedpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('feed_type', models.CharField(blank=True, choices=[('liste', "Director's Favourite"), ('topic', 'Festival Winner Movies'), ('blog', 'Blog Post'), ('movie', 'Movie')], max_length=3, null=True)),
                ('page_link', models.URLField(null=True)),
                ('cover_poster', models.ImageField(blank=True, help_text='minimum 500px for the shorter dimension', upload_to=feed.models.horizontal_upload_path)),
                ('is_published', models.BooleanField(default=False)),
                ('liste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='items.List')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='items.Topic')),
            ],
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='liste',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='topic',
        ),
        migrations.DeleteModel(
            name='FeedPost',
        ),
    ]
