# Generated by Django 2.0.5 on 2019-12-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_auto_20191207_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='feed_type',
            field=models.CharField(blank=True, choices=[('liste', 'List'), ('topic', 'Topic'), ('blog', 'Blog Post'), ('movie', 'Movie')], max_length=6, null=True),
        ),
    ]
