# Generated by Django 2.0.5 on 2019-12-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_auto_20191207_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='page_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
