# Generated by Django 2.0.5 on 2019-12-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_auto_20191207_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssfeed',
            name='page_link',
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='pathname',
            field=models.CharField(blank=True, help_text='page url without domain part.', max_length=50, null=True),
        ),
    ]
