# Generated by Django 2.0.5 on 2019-12-07 18:07

from django.db import migrations, models
import django.db.models.deletion
import feed.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0196_auto_20191207_2006'),
        ('feed', '0016_auto_20191207_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('feed_type', models.CharField(blank=True, choices=[('liste', 'List'), ('topic', 'Topic'), ('blog', 'Blog Post'), ('movie', 'Movie')], max_length=6, null=True)),
                ('pathname', models.CharField(blank=True, help_text='page url without domain part.', max_length=50, null=True)),
                ('cover_poster', models.ImageField(blank=True, help_text='minimum 500px for the shorter dimension', upload_to=feed.models.horizontal_upload_path)),
                ('is_published', models.BooleanField(default=False)),
                ('liste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='items.List')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='items.Topic')),
            ],
        ),
    ]
