# Generated by Django 2.0.5 on 2019-12-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_rssfeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssfeed',
            name='liste',
        ),
        migrations.RemoveField(
            model_name='rssfeed',
            name='topic',
        ),
        migrations.DeleteModel(
            name='RSSFeed',
        ),
    ]
