# Generated by Django 2.0.5 on 2019-02-06 14:01

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieArchive',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dummyset', django_mysql.models.SetTextField(models.IntegerField(), default=set, size=None)),
                ('userset', django_mysql.models.SetTextField(models.IntegerField(), default=set, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='UserArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(choices=[('p', 'profile'), ('d', 'dummy')], max_length=1)),
                ('movieset', django_mysql.models.SetTextField(models.IntegerField(), size=None)),
                ('ratings', django_mysql.models.JSONField(default=dict)),
                ('average', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
    ]
