# Generated by Django 2.0.5 on 2019-02-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userarchive',
            unique_together={('user_id', 'user_type')},
        ),
    ]
