# Generated by Django 2.0.5 on 2019-02-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20190206_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarchive',
            name='user_type',
            field=models.CharField(choices=[('u', 'user'), ('d', 'dummy')], max_length=1),
        ),
    ]
