# Generated by Django 2.0.5 on 2019-02-08 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0081_auto_20190208_1422'),
        ('archive', '0003_auto_20190208_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.IntegerField()),
                ('pearson', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('acs', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='base', to='items.Movie')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target', to='items.Movie')),
            ],
        ),
    ]
