# Generated by Django 2.0.5 on 2019-02-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0081_auto_20190208_1422'),
        ('archive', '0004_movsim'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movsim',
            unique_together={('base', 'target')},
        ),
    ]
