# Generated by Django 2.0.5 on 2019-04-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_auto_20190208_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movsim',
            name='base',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movsim',
            name='target',
            field=models.IntegerField(default=0),
        ),
    ]
