# Generated by Django 2.0.5 on 2019-04-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_auto_20190416_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movsim',
            old_name='base',
            new_name='base_id',
        ),
        migrations.RenameField(
            model_name='movsim',
            old_name='target',
            new_name='target_id',
        ),
        migrations.AlterUniqueTogether(
            name='movsim',
            unique_together={('base_id', 'target_id')},
        ),
    ]
