# Generated by Django 2.0.5 on 2019-04-15 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20190416_0014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovSim',
        ),
    ]
