# Generated by Django 2.0.5 on 2019-04-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_movsim'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movsim',
            unique_together={('base_id', 'target_id')},
        ),
    ]
