# Generated by Django 2.0.5 on 2019-04-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_auto_20190416_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movsim',
            old_name='users',
            new_name='commons',
        ),
    ]
