# Generated by Django 2.0.5 on 2019-04-19 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_auto_20190416_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userarchive',
            name='average',
        ),
    ]
