# Generated by Django 2.0.5 on 2019-06-02 20:22

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_remove_userarchive_average'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmdbMovie',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('data', django_mysql.models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
