# Generated by Django 2.0.5 on 2019-06-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_tmdbmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmdbmovie',
            name='imdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tmdbmovie',
            name='movielens_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
