# Generated by Django 2.0.5 on 2019-06-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_auto_20190603_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmdbmovie',
            name='imdb_id',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
