# Generated by Django 2.0.5 on 2019-06-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_auto_20190603_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmdbmovie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
