# Generated by Django 2.0.5 on 2019-06-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_auto_20190603_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmdbmovie',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
