# Generated by Django 2.0.5 on 2019-06-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_tmdbmovie_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmdbmovie',
            name='movielens_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
