# Generated by Django 2.2 on 2019-06-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_auto_20190610_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmdbmovie',
            name='registered',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
