# Generated by Django 2.0.5 on 2019-08-25 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0135_auto_20190821_0206'),
        ('archive', '0020_tmdbmovie_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_similars', to='items.Movie')),
                ('similars', models.ManyToManyField(blank=True, null=True, related_name='content_similars_of', to='items.Movie')),
            ],
        ),
    ]
