# Generated by Django 2.0.5 on 2019-08-27 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0023_auto_20190827_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsimilarity',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_similar_object', to='items.Movie'),
        ),
    ]
