# Generated by Django 2.0.5 on 2019-09-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0024_auto_20190827_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmdbmovie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
