# Generated by Django 2.0.5 on 2018-10-15 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(help_text="Use Imdb Id, if exists. Otherwise use prefix 'pp' with 7 digit number. \nE.g: \n If Imdb Id=nm0000759  than enter 'nm0000759' as Id.\nOtherwise: enter like 'pp0000001' or 'pp1700001'.(2letter(pp) + 7digit)", max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('bio', models.CharField(max_length=1000, null=True)),
                ('job', models.CharField(choices=[('d', 'Director'), ('a', 'Actor/Actress'), ('w', 'Writer')], max_length=3, null=True)),
                ('born', models.DateField(blank=True, null=True)),
                ('died', models.DateField(blank=True, null=True)),
                ('data', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('relations', models.ManyToManyField(blank=True, related_name='_person_relations_+', to='persons.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('joined', models.DateField(blank=True, null=True)),
                ('born', models.DateField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('ratings', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('persons.person',),
        ),
    ]
