# Generated by Django 2.0.5 on 2018-10-22 14:38

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20181022_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ratings',
            field=django_mysql.models.JSONField(default=dict, verbose_name={'movie': {}}),
        ),
    ]
