# Generated by Django 2.0.5 on 2018-10-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_profile_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarked', to='items.Movie'),
        ),
    ]
