# Generated by Django 2.0.5 on 2018-10-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_auto_20181022_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='person/pictures/'),
        ),
    ]
