# Generated by Django 2.0.5 on 2018-10-22 20:02

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_person_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ratings',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
