# Generated by Django 2.0.5 on 2018-10-22 20:15

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_auto_20181022_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ratings',
            field=django_mysql.models.JSONField(default=dict, verbose_name={}),
        ),
    ]
