# Generated by Django 2.0.5 on 2018-10-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_auto_20181022_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow_director',
            field=models.ManyToManyField(related_name='follower', to='persons.Director'),
        ),
    ]
