# Generated by Django 2.0.5 on 2018-10-31 15:37

from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0012_auto_20181031_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pictures',
            field=models.ImageField(blank=True, upload_to=persons.models.person_image_upload_path),
        ),
    ]
