# Generated by Django 2.0.5 on 2018-10-31 15:52

from django.db import migrations, models
import django.db.models.deletion
import persons.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0013_auto_20181031_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, upload_to=persons.models.person_image_upload_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='pictures',
        ),
        migrations.AddField(
            model_name='personimage',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='persons.Person'),
        ),
    ]
