# Generated by Django 2.0.5 on 2018-10-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0014_auto_20181031_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personimage',
            name='info',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
