# Generated by Django 2.0.5 on 2018-11-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0017_auto_20181031_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follow_director',
        ),
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followers', to='persons.Person'),
        ),
    ]
