# Generated by Django 2.0.5 on 2018-11-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0018_auto_20181101_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follows',
            new_name='follow_person',
        ),
    ]
