# Generated by Django 2.0.5 on 2018-11-14 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0019_auto_20181115_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follow_person',
        ),
    ]
