# Generated by Django 2.0.5 on 2018-11-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0020_remove_profile_follow_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow_persons',
            field=models.ManyToManyField(blank=True, related_name='followers', to='persons.Person'),
        ),
    ]
