# Generated by Django 2.0.5 on 2018-11-29 03:57

from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0023_profile_follow_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='poster',
            field=models.ImageField(blank=True, upload_to=persons.models.person_image_upload_path),
        ),
    ]
