# Generated by Django 2.0.5 on 2018-11-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0024_person_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=False, help_text='if ready for show on web page make it true'),
        ),
    ]
