# Generated by Django 2.0.5 on 2018-12-04 20:49

from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0025_person_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='job',
            field=models.CharField(blank=True, choices=[('d', 'Director'), ('a', 'Actor/Actress'), ('w', 'Writer'), ('e', 'Editor')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='poster',
            field=models.ImageField(blank=True, upload_to=persons.models.person_poster_upload_path),
        ),
    ]
