# Generated by Django 2.0.5 on 2018-12-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0026_auto_20181204_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
