# Generated by Django 2.0.5 on 2018-12-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0027_auto_20181205_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='poster',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
