# Generated by Django 2.0.5 on 2018-12-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0029_auto_20181205_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('persons.person',),
        ),
    ]
