# Generated by Django 2.0.5 on 2018-12-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0030_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='job',
            field=models.CharField(blank=True, choices=[('d', 'Director'), ('a', 'Actor/Actress'), ('w', 'Writer'), ('e', 'Editor'), ('f', 'Director of Photography')], max_length=5, null=True),
        ),
    ]
