# Generated by Django 2.0.5 on 2018-12-06 14:51

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0065_auto_20181206_1747'),
        ('persons', '0031_auto_20181205_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, choices=[('d', 'Director'), ('a', 'Actor/Actress'), ('w', 'Writer'), ('e', 'Editor'), ('f', 'Director of Photography')], max_length=5, null=True)),
                ('data', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
            ],
        ),
    ]
