# Generated by Django 2.0.5 on 2018-12-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0032_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='character',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
