# Generated by Django 2.0.5 on 2018-12-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0033_crew_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='relations',
        ),
        migrations.AlterField(
            model_name='person',
            name='tmdb_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
