# Generated by Django 2.0.5 on 2018-12-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0034_auto_20181212_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.CharField(max_length=6000, null=True),
        ),
    ]
