# Generated by Django 2.0.5 on 2018-12-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0035_auto_20181212_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tmdb_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
