# Generated by Django 2.0.5 on 2018-12-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0036_auto_20181213_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='character',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
