# Generated by Django 2.0.5 on 2019-01-04 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0068_auto_20190102_1316'),
        ('persons', '0037_auto_20181213_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.List')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='persons.Profile')),
                ('target_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='persons.Profile')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Topic')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('profile', 'person'), ('profile', 'topic'), ('profile', 'target_profile'), ('profile', 'liste')},
        ),
    ]
