# Generated by Django 2.0.5 on 2019-01-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0038_auto_20190104_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='typeof',
            field=models.CharField(choices=[('u', 'Profile'), ('p', 'Person'), ('l', 'Liste'), ('t', 'Topic')], default='u', max_length=1),
            preserve_default=False,
        ),
    ]
