# Generated by Django 2.0.5 on 2019-01-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0068_auto_20190102_1316'),
        ('persons', '0040_auto_20190104_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='videos',
            field=models.ManyToManyField(related_name='fav', to='items.Video'),
        ),
    ]
