# Generated by Django 2.0.5 on 2019-01-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0068_auto_20190102_1316'),
        ('persons', '0041_profile_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_movies',
            field=models.ManyToManyField(related_name='liked', to='items.Movie'),
        ),
    ]
