# Generated by Django 2.0.5 on 2019-01-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0042_profile_liked_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
