# Generated by Django 2.0.5 on 2019-02-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0044_auto_20190122_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='...', max_length=140, null=True),
        ),
    ]
