# Generated by Django 2.0.5 on 2019-02-08 02:52

from django.db import migrations, models
import persons.profile


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0045_auto_20190203_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=persons.profile.avatar_upload_path),
        ),
    ]
