# Generated by Django 2.0.5 on 2019-02-09 15:00

from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0046_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='square_poster',
            field=models.ImageField(blank=True, upload_to=persons.models.director_square_poster_upload_path),
        ),
    ]
