# Generated by Django 2.0.5 on 2019-02-11 19:05

from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0047_person_square_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cover_poster',
            field=models.ImageField(blank=True, upload_to=persons.models.director_cover_poster_upload_path),
        ),
    ]
