# Generated by Django 2.0.5 on 2019-02-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0048_person_cover_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='short_bio',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
