# Generated by Django 2.0.5 on 2019-03-12 17:40

from django.db import migrations
import imagekit.models.fields
import persons.profile


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0050_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=persons.profile.avatar_upload_path),
        ),
    ]
