# Generated by Django 2.0.5 on 2019-03-12 17:46

from django.db import migrations, models
import persons.profile


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0051_auto_20190312_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=persons.profile.avatar_upload_path),
        ),
    ]
