# Generated by Django 2.0.5 on 2019-03-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0052_auto_20190312_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
