# Generated by Django 2.0.5 on 2019-03-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0053_auto_20190312_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='short_bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
