# Generated by Django 2.0.5 on 2019-03-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0054_auto_20190318_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
