# Generated by Django 2.0.5 on 2019-04-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0055_auto_20190318_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
