# Generated by Django 2.0.5 on 2019-05-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0059_auto_20190522_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('rm', 'rating'), ('bm', 'bookmark'), ('lm', 'like'), ('fp', 'follow-person'), ('fu', 'follow-user'), ('fl', 'follow-list')], max_length=2),
        ),
    ]
