# Generated by Django 2.0.5 on 2019-05-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0060_auto_20190522_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
