# Generated by Django 2.0.5 on 2019-05-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0062_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('rm', 'rating-movie'), ('bm', 'bookmark-movie'), ('lm', 'like-movie'), ('lv', 'like-video'), ('fp', 'follow-person'), ('fu', 'follow-user'), ('fl', 'follow-list')], max_length=2),
        ),
    ]
