# Generated by Django 2.0.5 on 2019-05-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0063_auto_20190522_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
