# Generated by Django 2.0.5 on 2019-05-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0064_activity_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
