# Generated by Django 2.0.5 on 2019-06-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0086_auto_20190312_2040'),
        ('persons', '0066_activity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crew',
            unique_together={('person', 'movie', 'job')},
        ),
    ]
