# Generated by Django 2.0.5 on 2019-07-27 22:00

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0067_auto_20190603_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ratings',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
