# Generated by Django 2.0.5 on 2019-07-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0068_auto_20190728_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookmarked', to='items.Movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_movies',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked', to='items.Movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, related_name='fav', to='items.Video'),
        ),
    ]
