# Generated by Django 2.0.5 on 2019-07-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0069_auto_20190728_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cognito_status',
            field=models.BooleanField(default=False),
        ),
    ]
