# Generated by Django 2.0.5 on 2019-07-30 17:00

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0070_profile_cognito_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cognito_tokens',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
