# Generated by Django 2.0.5 on 2019-07-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0071_profile_cognito_tokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cognito_status',
            new_name='cognito_registered',
        ),
        migrations.AddField(
            model_name='profile',
            name='cognito_verified',
            field=models.BooleanField(default=False),
        ),
    ]
