# Generated by Django 2.0.5 on 2019-07-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0072_auto_20190731_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cognito_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
