# Generated by Django 2.0.5 on 2019-08-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0073_profile_cognito_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='should_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
