# Generated by Django 2.0.5 on 2019-08-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0075_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='personimage',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personimage',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personimage',
            name='imdb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personimage',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personimage',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
