# Generated by Django 2.0.5 on 2019-08-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0076_auto_20190817_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personimage',
            name='person',
        ),
        migrations.DeleteModel(
            name='PersonImage',
        ),
    ]
