# Generated by Django 2.0.5 on 2019-08-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0081_auto_20190820_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='wiki',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wiki',
            field=models.URLField(blank=True, null=True),
        ),
    ]
