# Generated by Django 2.0.5 on 2019-08-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0082_auto_20190820_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='rich_data',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rich_data',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
