# Generated by Django 2.0.5 on 2019-08-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0083_auto_20190820_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='rich_data',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rich_data',
        ),
    ]
