# Generated by Django 2.0.5 on 2019-08-20 13:49

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0084_auto_20190820_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='rich_data',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rich_data',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
