# Generated by Django 2.0.5 on 2019-09-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0086_auto_20190820_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='main_page',
            field=models.BooleanField(default=False, help_text='Selected item will be showed on welcome screen'),
        ),
    ]
