# Generated by Django 2.0.5 on 2019-09-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0088_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
