# Generated by Django 2.0.5 on 2019-09-06 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0090_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='persons.Profile'),
        ),
    ]
