# Generated by Django 2.0.5 on 2019-09-11 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0091_auto_20190907_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('stdev', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='persons.Profile')),
            ],
        ),
    ]
