# Generated by Django 2.0.5 on 2019-09-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0092_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='stdev',
        ),
    ]
