# Generated by Django 2.0.5 on 2019-09-11 21:27

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0093_remove_statistics_stdev'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='actor_ids',
            field=django_mysql.models.ListTextField(models.CharField(max_length=12), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='statistics',
            name='actors_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='director_ids',
            field=django_mysql.models.ListTextField(models.CharField(max_length=12), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='statistics',
            name='directors_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='list_ids',
            field=django_mysql.models.ListTextField(models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='statistics',
            name='previous_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='tag_slugs',
            field=django_mysql.models.ListTextField(models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='statistics',
            name='tags_num',
            field=models.IntegerField(default=0),
        ),
    ]
