# Generated by Django 2.0.5 on 2019-09-12 13:29

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0094_auto_20190912_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='actors_num',
            new_name='actor_num',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='directors_num',
            new_name='director_num',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='tags_num',
            new_name='genre_num',
        ),
        migrations.AddField(
            model_name='statistics',
            name='genre_slugs',
            field=django_mysql.models.ListTextField(models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='statistics',
            name='tag_num',
            field=models.IntegerField(default=0),
        ),
    ]
