# Generated by Django 2.0.5 on 2019-09-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0095_auto_20190912_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
