# Generated by Django 2.0.5 on 2019-09-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0097_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='facebook_username',
            new_name='facebook_id',
        ),
        migrations.AddField(
            model_name='info',
            name='facebook_email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='info',
            name='facebook_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='info',
            name='facebook_sign',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='facebook_token',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
