# Generated by Django 2.0.5 on 2019-11-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0100_auto_20191102_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='connected_with_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='registered_with_facebook',
            field=models.BooleanField(default=False),
        ),
    ]
