# Generated by Django 2.0.5 on 2019-11-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0101_auto_20191105_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='seo_description',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='seo_description',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
    ]
