# Generated by Django 2.0.5 on 2020-01-24 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0105_person_important_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crews', to='items.Movie'),
        ),
    ]
