# Generated by Django 2.0.5 on 2020-03-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0106_auto_20200124_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='info',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
