# Generated by Django 2.0.5 on 2020-03-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0107_crew_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribe_mail',
            field=models.BooleanField(default=True),
        ),
    ]
