# Generated by Django 2.0.5 on 2019-12-08 03:40

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='tag',
            field=django_mysql.models.ListTextField(models.CharField(max_length=60), default=[], size=None),
        ),
    ]
