# Generated by Django 2.0.5 on 2019-12-08 03:47

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_rssfeed_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='tag',
            field=django_mysql.models.ListTextField(models.CharField(max_length=60), blank=True, default=[], null=True, size=None),
        ),
    ]
