# Generated by Django 2.0.5 on 2020-01-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_auto_20191208_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
