# Generated by Django 2.0.5 on 2020-01-13 22:25

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_post_important_page'),
        ('rss', '0004_rssfeed_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonRSSFeed',
            fields=[
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=70, null=True)),
                ('tag', django_mysql.models.ListTextField(models.CharField(max_length=60), blank=True, default=[], null=True, size=None)),
                ('pathname', models.CharField(blank=True, help_text='page url without domain part.', max_length=50, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='blog.Post')),
            ],
        ),
    ]
