# Generated by Django 2.0.5 on 2020-01-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0005_pythonrssfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonrssfeed',
            name='pathname',
            field=models.CharField(blank=True, help_text='page url without domain part.', max_length=80, null=True),
        ),
    ]
