export * from "./NavBar"
export * from "./ProfileCover"
export * from "./ProgressBar"
export * from "./AutoComplete"
export * from "./SimilarMovies"
export * from "./DoubleRangeSlider"
export * from "./VideoPlayer"
export * from "./Bot"
//export * from "./MovieCoverPanel"

//export * from "./Popup"